version: 4.0

id: remark-config
uid: 146657102

about:
  title: Remark Config
  alias: remark-config
  description: Remark config preset to configure remark-lint with some customization for usage at TELUS
  type: 'module'
  target: npm

contacts:
  - type: Project Owner
    name: Shimona Jain
    email: shimona.jain@telus.com

  - type: Team
    name: ptt-ti
    members_uri: https://github.com/orgs/telus/teams/ptt-ti/members
    repositories_uri: https://github.com/orgs/telus/teams/ptt-ti/repositories

environments:
  - type: production
    title: NPM Package
    uri: https://www.npmjs.com/package/@telus/remark-config

references:
  - title: git
    description: Source Code
    uri: https://github.com/telus/remark-config
