name: 'Publish package on merge to master'

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps
        run: npm ci

      - name: Publish package
        run: npx semantic-release
